version: '3.8'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    ports:
      - "8000:80"
    volumes:
      - ./:/app
    networks:
      - laravel
    entrypoint: ["/bin/sh", "-c", "php artisan key:generate && php-fpm"]

  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - laravel

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - laravel

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    entrypoint: ["/bin/sh", "-c", "while :; do php artisan schedule:work; sleep 60; done"]
    depends_on:
      - app

volumes:
  db-data:

networks:
  laravel:
